apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-angel
  namespace: angel
spec:
  storageClassName: database
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi