apiVersion: v1
kind: Service
metadata:
  labels:
    app: pages
  name: pages
  namespace: angel
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: pages
  type: NodePort